// Copyright (c) 2016, XMOS Ltd, All rights reserved

#define XTCP_BUFFERED_API 1
#define XTCP_VERBOSE_DEBUG

#define UIP_USE_AUTOIP 1
#define UIP_USE_DHCP 0

#define XTCP_EXCLUDE_UNLISTEN
#define XTCP_EXCLUDE_CONNECT
#define XTCP_EXCLUDE_BIND_REMOTE
#define XTCP_EXCLUDE_BIND_LOCAL
#define XTCP_EXCLUDE_SET_APPSTATE
#define XTCP_EXCLUDE_ABORT
#define XTCP_EXCLUDE_SET_POLL_INTERVAL
#define XTCP_EXCLUDE_JOIN_GROUP
#define XTCP_EXCLUDE_LEAVE_GROUP
#define XTCP_EXCLUDE_GET_MAC_ADDRESS
#define XTCP_EXCLUDE_GET_IPCONFIG
#define XTCP_EXCLUDE_ACK_RECV
#define XTCP_EXCLUDE_ACK_RECV_MODE
#define XTCP_EXCLUDE_PAUSE
#define XTCP_EXCLUDE_UNPAUSE

